### ISSUE TITLE
Seems to fail for very long error messages

### ISSUE THREAD

**Issue by michaeljones** [michaeljones/elm-make-server#1]
Most notably with the vim integration where it is asking for json and the json is truncated for some reason and so is invalid and cannot be used.

```
elm make src/Authoring.elm                                                                                      
undefined:1                                                                      
{"type":"compile-log","code":1,"stdout":[{"time":1515590233424,"text":"Detected errors in 2 modules.\n"}],"stderr":[{"time":1515590231899,"text":"-- TYPE"},{"time":1515590231899,"text":" MISMATCH -------------"},{
"time":1515590231910,"text":"-----"},{"time":1515590231910,"text":"---- ././src/Authoring/ProcessFlow/Update.elm\n\nTh"},{"time":1515590231926,"text":"e"},{"time":1515590231926,"text":" 24th and 25th branches of t
his `case` "},{"time":1515590231935,"text":"produ"},{"time":1515590231935,"text":"ce different types of val"},{"time":1515590231941,"text":"ues.\n\n"},{"time":1515590231942,"text":" 20|     case msg of\n 21|   "},
{"time":1515590231942,"text":"      "},{"time":1515590231942,"text":"SetLayout layout ->\n 22|           "},{"time":1515590231942,"text":"  { model | processFlowDa"},{"time":1515590231942,"text":"t"},{"time":15155
90231942,"text":"a = {"},{"time":1515590231942,"text":" processFlowData | layout = J"},{"time":1515590231942,"text":"ust layout } } !"},{"time":1515590231942,
                                                                                  
SyntaxError: Unexpected end of JSON input                                                        
    at JSON.parse (<anonymous>)                                                                      
    at Socket.<anonymous> (/home/michael/root/projects/elm-make-server/index.js:156:41)                   
    at emitOne (events.js:116:13)                                                            
    at Socket.emit (events.js:211:7)                                                                   
    at addChunk (_stream_readable.js:263:12)                                           
    at readableAddChunk (_stream_readable.js:250:11)                                                    
    at Socket.Readable.push (_stream_readable.js:208:10)                                                
    at TCP.onread (net.js:594:20)                            
Makefile:3: recipe for target 'all' failed                                                           
make: *** [all] Error 1  
```

**Comment by michaeljones** [comment]
Hopefully addressed in eb06e24755722fff41d8ba165a258865dc889bd8
